#!/usr/bin/env python3
"""render.py — turn a department's chat.yml into everything a deploy needs.

    render.py render <dept-dir> [--check]      chat.yml -> <dept-dir>/generated/
    render.py resolve --server <generated/servers/X.json> --default-domain <env domain> ...
                                              -> ARM parameters for infra/server.bicep (stdout)
    render.py urls <dept-dir> --default-domain <d>
                                              -> where every server/realm is reachable right now

`render` is pure: same chat.yml in, byte-identical files out, so `--check` can gate
CI on "generated/ is stale". Anything only known after Azure exists (the Container Apps
environment's default domain, the Entra client id when it lives in Key Vault, the
hostnames already bound, the IP rules already applied) is left as a {{placeholder}} and
filled by `resolve` at deploy time.

DNS: a server is `dns: pending` until its CNAMEs exist. While pending it is
served on its own *.azurecontainerapps.io name, which Azure already covers with TLS, so
an instance can be deployed, signed into and tested before any DNS exists. Flipping it
to `live` switches EXTERNAL_HOST (and, on a shared server, the realm hosts and the OIDC
callback host) to the real names.
"""
from __future__ import annotations

import argparse
import base64
import difflib
import ipaddress
import json
import re
import shutil
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml
from jsonschema import Draft202012Validator

sys.path.insert(0, str(Path(__file__).resolve().parent))
import zulip_reserved  # noqa: E402

TEMPLATE_ROOT = Path(__file__).resolve().parent.parent
SCHEMA_PATH = TEMPLATE_ROOT / "schema" / "chat.schema.json"
GENERATED = "generated"
HEADER_NOTE = "GENERATED by pu-shd/chat tools/render.py from chat.yml. Do not edit."

# Container Apps and jobs share a 32-character name limit.
ACA_NAME_MAX = 32
SOCIAL_AUTH_SUBDOMAIN = "auth"
# Zulip's SYSTEM_BOT_REALM: the internal realm every server creates for its system bots.
SYSTEM_BOT_REALM = "zulipinternal"
# zerver/forms.py check_subdomain_available and Realm.MAX_REALM_NAME_LENGTH.
REALM_SLUG_MIN = 3
REALM_NAME_MAX = 40
HEALTHCHECKS_PING_KEY_SECRET = "healthchecks-ping-key"

DEFAULT_CAMPUS_RANGES = [
    # Princeton campus, IPv4 only: Container Apps ingress rules do not take IPv6.
    "128.112.0.0/16",
    "140.180.0.0/16",
    "204.153.48.0/23",
    "66.180.176.0/24",
    "66.180.177.0/24",
    "66.180.180.0/22",
]
SERVER_DEFAULTS: dict[str, Any] = {
    "dns": "pending",
    "cpu": 2.0,
    "ip_gate": False,
    "easy_auth": False,
    "push_notifications": False,
    "data_quota_gib": 100,
}
EMAIL_PROVIDERS = {
    # Resend SMTP. Azure blocks outbound 25, so 587/STARTTLS.
    "resend": {"host": "smtp.resend.com", "port": 587, "user": "resend"},
    # Azure Communication Services Email: an Entra app's client secret authenticates, under
    # an SMTP username resource (acs-email.zsh creates both).
    "acs": {"host": "smtp.azurecomm.net", "port": 587},
}
ACS_MANAGED = "azure-managed"
# Paths Easy Auth must not intercept, or the mobile/desktop apps, bots, uploads and
# SCIM stop working. Everything here is reachable anonymously at the Easy Auth layer and
# is protected by Zulip itself.
EASY_AUTH_EXCLUDED_PATHS = [
    "/api/*", "/json/events", "/user_uploads/*", "/thumbnail*", "/avatar/*",
    "/static/*", "/scim/*", "/health", "/complete/*", "/accounts/login/*",
]


class ConfigError(Exception):
    pass


class PySecret:
    """Renders as get_secret("name") inside a Python settings literal."""

    def __init__(self, name: str) -> None:
        self.name = name


def pylit(value: Any) -> str:
    """Python literal for docker-zulip SETTING_* values (dicts pass through verbatim)."""
    if isinstance(value, PySecret):
        return f"get_secret({json.dumps(value.name)})"
    if value is True:
        return "True"
    if value is False:
        return "False"
    if value is None:
        return "None"
    if isinstance(value, (int, float)):
        return repr(value)
    if isinstance(value, str):
        return json.dumps(value)
    if isinstance(value, list):
        return "[" + ", ".join(pylit(v) for v in value) + "]"
    if isinstance(value, dict):
        return "{" + ", ".join(f"{json.dumps(k)}: {pylit(v)}" for k, v in sorted(value.items())) + "}"
    raise TypeError(f"no literal for {type(value)}")


def dump_json(obj: Any) -> str:
    return json.dumps(obj, indent=2, sort_keys=True) + "\n"


# --------------------------------------------------------------------------- loading


def load_config(dept_dir: Path) -> dict[str, Any]:
    path = dept_dir / "chat.yml"
    if not path.is_file():
        raise ConfigError(f"{path}: not found")
    try:
        cfg = yaml.safe_load(path.read_text())
    except yaml.YAMLError as exc:
        raise ConfigError(f"{path}: invalid YAML: {exc}") from exc
    if not isinstance(cfg, dict):
        raise ConfigError(f"{path}: top level must be a mapping")
    schema = json.loads(SCHEMA_PATH.read_text())
    errors = sorted(Draft202012Validator(schema).iter_errors(cfg), key=lambda e: list(e.absolute_path))
    if errors:
        lines = []
        for err in errors:
            where = "/".join(str(p) for p in err.absolute_path) or "(root)"
            lines.append(f"  {where}: {err.message}")
        raise ConfigError(f"{path}: schema validation failed:\n" + "\n".join(lines))
    if cfg["department"] != dept_dir.name:
        raise ConfigError(
            f"{path}: department '{cfg['department']}' must match its directory name '{dept_dir.name}'"
        )
    check_strings(cfg, path)
    return cfg


def check_strings(cfg: Any, path: Path) -> None:
    """Rules the schema cannot express on every string in chat.yml (keys included).

    JSON Schema `pattern` uses Python `re.search`, where `$` also matches before a
    trailing newline, so every pattern lets a final "\\n" through. And `{{`/`}}` would be
    taken for one of resolve's placeholders.
    """
    def walk(node: Any, where: list[str]) -> None:
        if isinstance(node, dict):
            for k, v in node.items():
                walk(k, where + [f"{k} (key)"])
                walk(v, where + [str(k)])
        elif isinstance(node, list):
            for i, v in enumerate(node):
                walk(v, where + [str(i)])
        elif isinstance(node, str):
            at = "/".join(where) or "(root)"
            if re.search(r"[\x00-\x1f\x7f]", node):
                raise ConfigError(f"{path}: {at}: contains a control character (newline, tab, ...): {node!r}")
            if "{{" in node or "}}" in node:
                raise ConfigError(f"{path}: {at}: may not contain '{{{{' or '}}}}' (reserved for render placeholders): {node!r}")
    walk(cfg, [])


def available_themes() -> set[str]:
    return {p.parent.name for p in (TEMPLATE_ROOT / "image" / "themes").glob("*/theme.css")}


def check_theme(name: str | None, where: str) -> str | None:
    if name in (None, "default"):
        return None
    if name not in available_themes():
        raise ConfigError(f"{where}: theme '{name}' is not in this template (have: {', '.join(sorted(available_themes())) or 'none'})")
    return name


def is_reserved(slug: str) -> bool:
    """Mirror of zerver/lib/name_restrictions.is_reserved_subdomain (settings-free parts)."""
    if slug in (SOCIAL_AUTH_SUBDOMAIN, SYSTEM_BOT_REALM):
        return True
    for pool in (zulip_reserved.ZULIP_RESERVED_SUBDOMAINS, zulip_reserved.GENERIC_RESERVED_SUBDOMAINS):
        if slug in pool or (slug.endswith("s") and slug[:-1] in pool):
            return True
    return False


# --------------------------------------------------------------------------- model


@dataclass
class Rendered:
    platform: dict[str, Any]
    servers: dict[str, dict[str, Any]]
    index: dict[str, Any]
    warnings: list[str]


def platform_spec(cfg: dict[str, Any]) -> dict[str, Any]:
    az = cfg["azure"]
    prefix = az["prefix"]
    names = az.get("names", {})
    compact = re.sub(r"[^a-z0-9]", "", prefix)
    try:
        vnet = ipaddress.ip_network(az.get("vnet_cidr", "10.60.0.0/16"))
    except ValueError as exc:
        loose = ipaddress.ip_network(az["vnet_cidr"], strict=False)
        raise ConfigError(f"azure.vnet_cidr {az['vnet_cidr']} has host bits set; use the network address {loose}") from exc
    if vnet.prefixlen > 22:
        raise ConfigError(f"azure.vnet_cidr {vnet} is too small; need at least a /22")
    aca_subnet = next(vnet.subnets(new_prefix=23))
    pg_subnet = list(aca_subnet.supernet(new_prefix=22).subnets(new_prefix=24))[2]
    pg_name = names.get("postgres", f"{prefix}-pg")
    provider = cfg["email"]["provider"]
    email = {"provider": provider, **EMAIL_PROVIDERS.get(provider, {})}
    acs = None
    if provider == "acs":
        a = cfg["email"].get("acs")
        if not a:
            raise ConfigError("email: provider 'acs' needs email.acs.domain (a custom domain, or azure-managed)")
        managed = a["domain"] == ACS_MANAGED
        acs = {
            "email_service": f"{prefix}-email",
            "communication_service": f"{prefix}-acs",
            "domain": "AzureManagedDomain" if managed else a["domain"],
            "managed": managed,
            "data_location": a.get("data_location", "United States"),
            "smtp_username_resource": f"{prefix}-smtp",
            "entra_app": f"{prefix}-acs-smtp",
        }
        email["user"] = f"{prefix}-smtp"
        if managed:
            if "from" in cfg["email"]:
                raise ConfigError("email: with acs.domain azure-managed the sender is Azure's DoNotReply@<domain>; drop email.from")
            email["from"] = "{{acs_mail_from}}"
        else:
            frm = cfg["email"].get("from")
            if not frm or frm.rsplit("@", 1)[1] != a["domain"]:
                raise ConfigError(f"email: with acs.domain {a['domain']}, email.from must be an address @{a['domain']}")
            # ACS sends only from configured senders. A new custom domain has just
            # donotreply@; others need an approved quota increase first.
            if frm.split("@")[0].lower() != "donotreply" and not a.get("custom_senders"):
                raise ConfigError(f"email: ACS sends from donotreply@{a['domain']} until Microsoft approves a quota "
                                  "increase; use that address, or set email.acs.custom_senders: true once approved")
            email["from"] = frm
        acs["senders"] = [] if managed or email["from"].split("@")[0].lower() == "donotreply" \
            else sorted({email["from"].split("@")[0]})
    for key in ("host", "port", "user"):
        if key in cfg["email"]:
            if provider == "acs":
                raise ConfigError(f"email.{key} is set by provider 'acs'; remove it")
            email[key] = cfg["email"][key]
    missing = [k for k in ("host", "port", "user") if k not in email]
    if missing:
        raise ConfigError(f"email: provider 'smtp' needs {', '.join(missing)}")
    if provider != "acs":
        if "from" not in cfg["email"]:
            raise ConfigError(f"email: provider '{provider}' needs email.from")
        email["from"] = cfg["email"]["from"]
    # Only the display name of ACS sender usernames (deploy-platform.zsh). Zulip's
    # computed_settings sets DEFAULT_FROM_EMAIL = ZULIP_ADMINISTRATOR unconditionally, so
    # it is not passed to Zulip at all.
    email["from_name"] = cfg["email"].get("from_name", f"{cfg['department'].upper()} Chat")
    gate = cfg.get("ip_gate", {})
    return {
        "_note": HEADER_NOTE,
        "department": cfg["department"],
        "tenant_id": az["tenant_id"],
        "subscription_id": az["subscription_id"],
        "region": az["region"],
        "prefix": prefix,
        "resource_group": names.get("resource_group", f"{prefix}-rg"),
        "names": {
            "environment": f"{prefix}-env",
            "key_vault": names.get("key_vault", f"{prefix}-kv"),
            "storage": names.get("storage", (compact + "data")[:24]),
            "registry": names.get("registry", (compact + "acr")[:50]),
            "postgres": pg_name,
            "log_analytics": f"{prefix}-logs",
            "identity": f"{prefix}-id",
            "vnet": f"{prefix}-vnet",
            "github_app": f"{prefix}-github-actions",
        },
        "network": {"vnet": str(vnet), "aca_subnet": str(aca_subnet), "pg_subnet": str(pg_subnet)},
        "postgres": {
            "host": f"{pg_name}.postgres.database.azure.com",
            "admin_user": "chatadmin",
            "sku": az.get("postgres_sku", "Standard_B1ms"),
            "version": "17",
        },
        "github": cfg["github"],
        "admin_email": cfg["admin_email"],
        "email": email,
        "acs": acs,
        "healthchecks": healthchecks_base(cfg),
        "rate_limits": rate_limits_spec(cfg, gate),
        "ip_gate": {
            "enabled": gate.get("enabled", True),
            "prefix_mode": gate.get("prefix_mode", "vendor"),
            "repo": gate.get("repo", "PrincetonUniversity/pugwips"),
            "campus_ranges": gate.get("campus_ranges", DEFAULT_CAMPUS_RANGES),
            "extra_ranges": gate.get("extra_ranges", []),
            "fallback_url": gate.get("fallback_url"),
            "snapshot": gate.get("snapshot", "pugwips-snapshot.json"),
            "snapshot_max_age_days": gate.get("snapshot_max_age_days", 30),
        },
    }


RATE_LIMIT_DEFAULTS = {
    # Generous: many VPN users share a handful of Prisma Access egress addresses, and a
    # Zulip client polls /json/events continuously and sends a request per action.
    "enabled": True, "auth_per_minute": 20, "auth_burst": 30, "api_per_second": 50, "api_burst": 500,
}


def rate_limits_spec(cfg: dict[str, Any], gate: dict[str, Any]) -> dict[str, Any]:
    rl = {**RATE_LIMIT_DEFAULTS, **cfg.get("rate_limits", {})}
    rl["exempt_ranges"] = rl.get("exempt_ranges", gate.get("campus_ranges", DEFAULT_CAMPUS_RANGES))
    return rl


def healthchecks_base(cfg: dict[str, Any]) -> dict[str, Any]:
    hc = cfg.get("healthchecks", {})
    return {
        "enabled": bool(hc.get("enabled", False)),
        "ping_base": hc.get("ping_base", "https://hc-ping.com"),
        "api_base": hc.get("api_base", "https://healthchecks.io/api/v3"),
        "health_interval_minutes": hc.get("health_interval_minutes", 5),
        "tags": sorted(set(hc.get("tags", []) + ["chat", cfg["department"]])),
        "checks": [],
    }


def hc_check(slug: str, name: str, desc: str, timeout: int, grace: int, tags: list[str]) -> dict[str, Any]:
    return {"slug": slug, "name": name, "desc": desc, "timeout": timeout, "grace": grace, "tags": tags}


def validate_snapshot(path: Path) -> None:
    try:
        data = json.loads(path.read_text())
    except (OSError, json.JSONDecodeError) as exc:
        raise ConfigError(f"{path}: unreadable pugwips snapshot: {exc}") from exc
    if not isinstance(data, dict) or not data.get("snapshot_date"):
        raise ConfigError(f"{path}: snapshot must be an object with a snapshot_date")
    if "gateways" not in data and not (data.get("prefix_mode") and data.get("prefixes")):
        raise ConfigError(f"{path}: snapshot needs either gateways{{}} (a gateways.json copy) or prefix_mode + prefixes[]")


def render_config(cfg: dict[str, Any], dept_dir: Path) -> Rendered:
    warnings: list[str] = []
    plat = platform_spec(cfg)
    prefix = plat["prefix"]
    defaults = {**SERVER_DEFAULTS, **cfg.get("defaults", {})}
    tenant = plat["tenant_id"]

    servers_cfg: dict[str, dict[str, Any]] = cfg["servers"]
    all_hosts: dict[str, str] = {}
    all_slugs: dict[str, str] = {}

    def claim_host(host: str, owner: str) -> None:
        if host in all_hosts:
            raise ConfigError(f"hostname {host} is used by both {all_hosts[host]} and {owner}")
        all_hosts[host] = owner

    def claim_slug(slug: str, owner: str) -> None:
        if slug in all_slugs:
            raise ConfigError(f"slug '{slug}' is used by both {all_slugs[slug]} and {owner}")
        if is_reserved(slug):
            raise ConfigError(f"{owner}: slug '{slug}' is reserved by Zulip; pick another")
        all_slugs[slug] = owner

    # Which dedicated server carries the chat.<dept>/<slug> redirects.
    redir_cfg = cfg.get("redirects", {})
    redirects_enabled = redir_cfg.get("enabled", True)
    host_server = redir_cfg.get("host_server")
    if redirects_enabled and host_server is None:
        roots = [n for n, s in servers_cfg.items() if s["kind"] == "dedicated" and "slug" not in s]
        if len(roots) == 1:
            host_server = roots[0]
        elif len(roots) > 1:
            raise ConfigError(
                f"several dedicated servers without a slug ({', '.join(sorted(roots))}); "
                "set redirects.host_server"
            )
        else:
            redirects_enabled = False
    if redirects_enabled:
        if host_server not in servers_cfg:
            raise ConfigError(f"redirects.host_server '{host_server}' is not a server")
        if servers_cfg[host_server]["kind"] != "dedicated":
            raise ConfigError(f"redirects.host_server '{host_server}' must be a dedicated server")

    if "from_name" in cfg["email"]:
        warnings.append("email.from_name has no effect on Zulip's mail (Zulip always sends From ZULIP_ADMINISTRATOR or "
                        "NOREPLY_EMAIL_ADDRESS and ignores DEFAULT_FROM_EMAIL); it is only the display name of ACS "
                        "sender usernames. Remove it unless that is what you want")
    if plat["acs"]:
        warnings.append("email: Microsoft retires ACS Email on 2028-09-30 and blocks new ACS customers from 2026-10-23 "
                        "(create the resource before then, or choose another provider); plan a move to Resend or M365 "
                        "High Volume Email (provider: smtp)")
        if plat["acs"]["managed"]:
            warnings.append("email: the ACS Azure-managed domain is limited to 5 mails/minute and 10/hour (not raisable); "
                            "invitations and notifications will be dropped beyond that — use it only as a stopgap")
        else:
            warnings.append("email: ACS custom domains start at 30 mails/minute and 100/hour; request an increase "
                            "(Azure support: Service and subscription limits) before a large realm goes live")
        if plat["admin_email"] != plat["email"]["from"]:
            warnings.append(f"email: Zulip sends some mail From admin_email ({plat['admin_email']}); ACS rejects senders "
                            "that are not configured on its domain, so those messages will fail")
    admin_domain = plat["admin_email"].rsplit("@", 1)[1]
    from_domain = (plat["acs"]["domain"] + ".azurecomm.net (Azure-managed)") if plat["acs"] and plat["acs"]["managed"] \
        else plat["email"]["from"].rsplit("@", 1)[1]
    if admin_domain != from_domain:
        warnings.append(
            f"admin_email is @{admin_domain} but mail is sent as @{from_domain}: Zulip sends some mail "
            f"from ZULIP_ADMINISTRATOR, so {admin_domain} must also be a verified sending domain "
            "at the mail provider, or use an admin address on the sending domain"
        )

    servers: dict[str, dict[str, Any]] = {}
    redirect_targets: list[dict[str, str]] = []
    gated_any = False

    for name in sorted(servers_cfg):
        scfg = servers_cfg[name]
        s = {**defaults, **scfg}
        app_name = f"{prefix}-{name}"
        jobs = {"mgmt": f"{app_name}-mgmt", "dbinit": f"{app_name}-dbinit", "hc": f"{app_name}-hc"}
        for n in [app_name, *jobs.values()]:
            if len(n) > ACA_NAME_MAX:
                raise ConfigError(
                    f"servers.{name}: Azure name '{n}' exceeds {ACA_NAME_MAX} characters; "
                    "shorten azure.prefix or the server name"
                )
        db = f"zulip_{name.replace('-', '_')}"
        realms: list[dict[str, Any]] = []
        hosts: list[str] = []
        server_theme = check_theme(s.get("theme"), f"servers.{name}")
        themes: list[dict[str, Any]] = []
        if s["kind"] == "dedicated":
            claim_host(s["host"], f"servers.{name}")
            check_realm_name(s["realm"]["name"], f"servers.{name}.realm")
            if server_theme:
                themes.append({"host": s["host"], "preview": True, "theme": server_theme})
            hosts.append(s["host"])
            realms.append({
                "slug": "", "name": s["realm"]["name"], "owner": s["realm"]["owner"],
                "active": True, "live_host": s["host"], "preview": True,
            })
            if "slug" in s:
                claim_slug(s["slug"], f"servers.{name}")
                redirect_targets.append({"slug": s["slug"], "server": name, "realm": ""})
            external_live = s["host"]
            preview_realm = ""
            oidc_callback_live = f"https://{s['host']}/complete/oidc/"
        else:
            ext = s["external_host"]
            auth_host = f"{SOCIAL_AUTH_SUBDOMAIN}.{ext}"
            claim_host(ext, f"servers.{name}")
            claim_host(auth_host, f"servers.{name} (OIDC callback)")
            if server_theme:
                themes += [{"host": ext, "preview": False, "theme": server_theme},
                           {"host": auth_host, "preview": False, "theme": server_theme}]
            hosts += [ext, auth_host]
            active = [r for r in s["realms"] if r.get("active", True)]
            if not active:
                raise ConfigError(f"servers.{name}: needs at least one active realm")
            preview_realm = s.get("preview_realm", active[0]["slug"])
            rd = s["realm_domain"]
            if rd != ext and rd.endswith("." + ext):
                raise ConfigError(
                    f"servers.{name}: realm_domain {rd} is under external_host {ext}; Zulip strips .{ext} from a "
                    f"request's host before it looks at REALM_HOSTS, so <slug>.{rd} would be routed to the wrong realm. "
                    f"Use realm_domain {ext} or a domain that is not under it"
                )
            for r in s["realms"]:
                where = f"servers.{name}.realms[{r['slug']}]"
                if len(r["slug"]) < REALM_SLUG_MIN:
                    raise ConfigError(f"{where}: realm slug '{r['slug']}' is too short; Zulip needs at least "
                                      f"{REALM_SLUG_MIN} characters")
                check_realm_name(r["name"], where)
                claim_slug(r["slug"], where)
                live_host = f"{r['slug']}.{s['realm_domain']}"
                is_active = r.get("active", True)
                if is_active:
                    realm_theme = check_theme(r["theme"], f"servers.{name}.realms[{r['slug']}]") if "theme" in r \
                        else server_theme
                    if realm_theme:
                        themes.append({"host": live_host, "preview": r["slug"] == preview_realm, "theme": realm_theme})
                    claim_host(live_host, f"servers.{name}.realms[{r['slug']}]")
                    hosts.append(live_host)
                    redirect_targets.append({"slug": r["slug"], "server": name, "realm": r["slug"]})
                realms.append({
                    "slug": r["slug"], "name": r["name"], "owner": r["owner"], "active": is_active,
                    "live_host": live_host, "preview": r["slug"] == preview_realm,
                })
            if preview_realm not in {r["slug"] for r in active}:
                raise ConfigError(f"servers.{name}: preview_realm '{preview_realm}' is not an active realm")
            external_live = ext
            oidc_callback_live = f"https://{auth_host}/complete/oidc/"

        if s["ip_gate"] and not plat["ip_gate"]["enabled"]:
            raise ConfigError(f"servers.{name}: ip_gate is true but ip_gate.enabled is false for the department")
        if s["ip_gate"]:
            gated_any = True
            if s["dns"] == "live" and "cert" not in s:
                raise ConfigError(
                    f"servers.{name}: ip_gate with dns: live needs cert.key_vault_certificate — "
                    "managed certificates cannot be issued or renewed while the IP gate blocks DigiCert"
                )
        if s["easy_auth"]:
            warnings.append(
                f"servers.{name}: easy_auth only guards the web UI; {', '.join(EASY_AUTH_EXCLUDED_PATHS)} "
                "stay reachable and are protected by Zulip's own login"
            )
        if s["ip_gate"] and not s["easy_auth"]:
            warnings.append(
                f"servers.{name}: ip_gate blocks the mobile apps for anyone off campus and off VPN"
            )
        # A shared server's Entra app admits everyone assigned to it into EVERY realm on
        # it, so there accounts are created by invitation unless chat.yml says otherwise.
        entra = {"client_id": None, "allowed_group_id": None, "auto_signup": s["kind"] == "dedicated",
                 **s.get("entra", {})}
        if entra["client_id"] is None:
            warnings.append(f"servers.{name}: entra.client_id not pinned; deploy reads {name}-oidc-client-id from Key Vault")

        hc = plat["healthchecks"]
        hc_server = {"enabled": hc["enabled"], "health": f"{prefix}-{name}-health", "web": f"{prefix}-{name}-web",
                     "ip_gate": f"{prefix}-{name}-ip-gate" if s["ip_gate"] else None}
        if hc["enabled"]:
            every = hc["health_interval_minutes"] * 60
            tags = hc["tags"] + [name]
            hc["checks"] += [
                hc_check(hc_server["health"], f"{name}: Zulip /health",
                         f"{app_name}: the -hc job calls /health inside the environment every "
                         f"{hc['health_interval_minutes']} min", every, max(3 * every, 900), tags),
                hc_check(hc_server["web"], f"{name}: reachable from the internet",
                         f"{app_name}: daily keepalive from GitHub Actions (realm answers, Entra sign-in "
                         "redirect, TLS and client-secret expiry)", 86400, 6 * 3600, tags),
            ]
            if s["ip_gate"]:
                hc["checks"].append(hc_check(hc_server["ip_gate"], f"{name}: IP gate refresh",
                                             f"{app_name}: daily pugwips allowlist refresh", 86400, 6 * 3600, tags))

        settings = zulip_settings(plat, s, name, db, tenant, entra, preview_realm)
        for key, val in settings.items():
            if "{{" not in val:  # the rest is checked once resolve fills it in
                check_setting(f"servers.{name}", key, val)
        servers[name] = {
            "_note": HEADER_NOTE,
            "name": name,
            "kind": s["kind"],
            "dns": s["dns"],
            "app_name": app_name,
            "jobs": jobs,
            "database": {"name": db, "user": db},
            "share": f"{name}-data",
            "env_storage": f"{name}-data",
            "cpu": float(s["cpu"]),
            "memory": f"{float(s['cpu']) * 2:g}Gi",
            "data_quota_gib": s["data_quota_gib"],
            "ip_gate": bool(s["ip_gate"]),
            "healthchecks": hc_server,
            "easy_auth": bool(s["easy_auth"]),
            "easy_auth_excluded_paths": EASY_AUTH_EXCLUDED_PATHS if s["easy_auth"] else [],
            "push_notifications": bool(s["push_notifications"]),
            "cert": s.get("cert"),
            "entra": entra,
            "external_host_live": external_live,
            "hosts": hosts,
            "oidc_callback_live": oidc_callback_live,
            "preview_realm": preview_realm,
            "realms": realms,
            "redirects": [],
            "themes": themes,
            "settings": settings,
            # Least privilege: each identity may read only these Key Vault secrets
            # (granted per secret by grant-access.zsh; deploy-server.zsh checks them).
            "identities": {
                "app": {"name": f"{app_name}-id", "secrets": sorted(
                    [f"{name}-secret-key", f"{name}-postgres-password", f"{name}-redis-password",
                     f"{name}-rabbitmq-password", f"{name}-memcached-password", f"{name}-oidc-secret",
                     "email-password"])},
                "db": {"name": f"{app_name}-db-id", "secrets": sorted([f"{name}-postgres-password", "pg-admin-password"])},
                # The -hc job: it only pings Healthchecks.
                **({"hc": {"name": f"{app_name}-hc-id", "secrets": [HEALTHCHECKS_PING_KEY_SECRET]}}
                   if plat["healthchecks"]["enabled"] else {}),
            },
            "key_vault_secrets": {
                "secret-key": f"{name}-secret-key",
                "postgres-password": f"{name}-postgres-password",
                "redis-password": f"{name}-redis-password",
                "rabbitmq-password": f"{name}-rabbitmq-password",
                "memcached-password": f"{name}-memcached-password",
                "oidc-secret": f"{name}-oidc-secret",
                "email-password": "email-password",
                "pg-admin-password": "pg-admin-password",
            },
        }

    check_unique_names(plat, servers)

    hc = plat["healthchecks"]
    if hc["enabled"]:
        hc["checks"].append(hc_check(f"{prefix}-updates", "update check",
                                     "weekly: newer pu-shd/chat release / pugwips snapshot (config repo)",
                                     7 * 86400, 2 * 86400, hc["tags"]))
        hc["checks"].sort(key=lambda c: c["slug"])
        warnings.append("healthchecks: Key Vault needs healthchecks-ping-key and GitHub needs HEALTHCHECKS_PING_KEY; "
                        "add healthchecks-api-key to have healthchecks.zsh create the checks with these schedules")

    if redirects_enabled:
        servers[host_server]["redirects"] = sorted(redirect_targets, key=lambda r: r["slug"])
        for r in redirect_targets:
            if r["slug"] in zulip_reserved.ZULIP_ROUTE_SEGMENTS:
                raise ConfigError(f"slug '{r['slug']}' would shadow the Zulip route /{r['slug']} on {host_server}")

    if gated_any:
        snap = dept_dir / plat["ip_gate"]["snapshot"]
        if not plat["ip_gate"]["fallback_url"] and not snap.is_file():
            raise ConfigError(
                f"ip_gate is on but there is no static fallback: set ip_gate.fallback_url or commit {snap.name}"
            )
        if snap.is_file():
            validate_snapshot(snap)

    index = {
        "_note": HEADER_NOTE,
        "department": plat["department"],
        "resource_group": plat["resource_group"],
        "redirect_host": host_server if redirects_enabled else None,
        "servers": sorted(servers),
    }
    return Rendered(plat, servers, index, warnings)


def check_realm_name(realm_name: str, where: str) -> None:
    if len(realm_name) > REALM_NAME_MAX:
        raise ConfigError(f"{where}: realm name {realm_name!r} is {len(realm_name)} characters; "
                          f"Zulip allows at most {REALM_NAME_MAX}")


def check_unique_names(plat: dict[str, Any], servers: dict[str, dict[str, Any]]) -> None:
    """Every name derived from server names must be unique across the department.

    Names are built by appending suffixes to <prefix>-<server>, so one server's derived
    name can equal another's (server x's x-db-id identity is server x-db's app identity;
    server a's a-mgmt job is server a-mgmt's app). Names shared on purpose by every
    server (email-password, ...) are claimed by the department and may repeat.
    """
    prefix = plat["prefix"]
    claimed: dict[tuple[str, str], str] = {}

    def claim(kind: str, value: str, owner: str) -> None:
        prev = claimed.setdefault((kind, value), owner)
        if prev != owner:
            raise ConfigError(f"{kind} name '{value}' is derived for both {prev} and {owner}; rename one of the servers")

    dept = "the department"
    claim("managed identity", plat["names"]["identity"], f"{dept} (platform identity)")
    shared_secrets = {"email-password", "pg-admin-password", HEALTHCHECKS_PING_KEY_SECRET}
    for secret in shared_secrets:
        claim("Key Vault secret", secret, f"{dept} (shared secret)")
    claim("Healthchecks slug", f"{prefix}-updates", f"{dept} (update check)")
    for name, spec in sorted(servers.items()):
        own = f"servers.{name}"
        claim("container app/job", spec["app_name"], f"{own} (app)")
        for job, jname in sorted(spec["jobs"].items()):
            claim("container app/job", jname, f"{own} ({job} job)")
        for kind, ident in sorted(spec["identities"].items()):
            claim("managed identity", ident["name"], f"{own} ({kind} identity)")
        secrets = {s for ident in spec["identities"].values() for s in ident["secrets"]}
        # Also the ones deploy/entra-app.zsh keep per server outside key_vault_secrets.
        secrets |= {*spec["key_vault_secrets"].values(), f"{name}-oidc-client-id", f"{name}-custom-domains"}
        for secret in sorted(secrets - shared_secrets):
            claim("Key Vault secret", secret, f"{own} (secret)")
        for check in ("health", "web", "ip_gate"):
            if spec["healthchecks"][check]:
                claim("Healthchecks slug", spec["healthchecks"][check], f"{own} ({check} check)")
        claim("Postgres database/role", spec["database"]["name"], f"{own} (database)")
        if spec["database"]["user"] != spec["database"]["name"]:
            claim("Postgres database/role", spec["database"]["user"], f"{own} (database user)")
        claim("storage share", spec["share"], f"{own} (share)")
        claim("environment storage", spec["env_storage"], f"{own} (environment storage)")


def zulip_settings(plat, s, name, db, tenant, entra, preview_realm) -> dict[str, str]:
    """docker-zulip environment (non-secret). {{...}} are filled by `resolve`."""
    email = plat["email"]
    rl = plat["rate_limits"]
    idp = {
        "entra": {
            "oidc_url": f"https://login.microsoftonline.com/{tenant}/v2.0",
            "display_name": "Princeton (Microsoft Entra ID)",
            "display_icon": "/static/images/authentication_backends/microsoft-icon.png",
            "client_id": "{{oidc_client_id}}",
            "secret": PySecret("social_auth_oidc_secret"),
            "auto_signup": bool(entra["auto_signup"]),
        }
    }
    env = {
        "SETTING_EXTERNAL_HOST": "{{external_host}}",
        "SETTING_ZULIP_ADMINISTRATOR": plat["admin_email"],
        "SETTING_REMOTE_POSTGRES_HOST": plat["postgres"]["host"],
        "SETTING_REMOTE_POSTGRES_PORT": "5432",
        "SETTING_REMOTE_POSTGRES_SSLMODE": "require",
        "CONFIG_postgresql__database_name": db,
        "CONFIG_postgresql__database_user": db,
        # Sidecars share the replica's network namespace.
        "SETTING_REDIS_HOST": "127.0.0.1",
        "SETTING_RABBITMQ_HOST": "127.0.0.1",
        "SETTING_MEMCACHED_LOCATION": "127.0.0.1:11211",
        "SETTING_EMAIL_HOST": email["host"],
        "SETTING_EMAIL_HOST_USER": email["user"],
        "SETTING_EMAIL_PORT": str(email["port"]),
        "SETTING_EMAIL_USE_TLS": "True" if email["port"] != 465 else "False",
        "SETTING_EMAIL_USE_SSL": "True" if email["port"] == 465 else "False",
        "SETTING_NOREPLY_EMAIL_ADDRESS": email["from"],
        "SETTING_ADD_TOKENS_TO_NOREPLY_ADDRESS": "False",
        "ZULIP_AUTH_BACKENDS": "GenericOpenIdConnectBackend",
        "SETTING_SOCIAL_AUTH_OIDC_ENABLED_IDPS": pylit(idp),
        "SETTING_SOCIAL_AUTH_OIDC_FULL_NAME_VALIDATED": "True",
        # TLS ends at Container Apps ingress; trust its forwarded headers from the
        # environment's subnet only.
        "CERTIFICATES": "",
        "LOADBALANCER_IPS": plat["network"]["aca_subnet"],
        # Small replicas: one process for all queue workers.
        "CONFIG_application_server__queue_workers_multiprocess": "false",
        "ZULIP_RUN_POST_SETUP_SCRIPTS": "True",
        "CHAT_REDIRECTS_B64": "{{redirects_b64}}",
        # Parameters only: chat-entrypoint builds the nginx limit_req config from these.
        "CHAT_RATE_LIMITS": (f"auth:{rl['auth_per_minute']}r/m:{rl['auth_burst']},"
                             f"api:{rl['api_per_second']}r/s:{rl['api_burst']}") if rl["enabled"] else "",
        "CHAT_RATE_LIMIT_EXEMPT": " ".join(rl["exempt_ranges"]) if rl["enabled"] else "",
        "CHAT_SERVER_NAME": name,
        "CHAT_THEMES": "{{themes}}",
    }
    if s["kind"] == "shared":
        env["SETTING_REALM_HOSTS"] = "{{realm_hosts}}"
        env["SETTING_SOCIAL_AUTH_SUBDOMAIN"] = "{{social_auth_subdomain}}"
        env["SETTING_ROOT_DOMAIN_LANDING_PAGE"] = "False"
    if s["push_notifications"]:
        env["SETTING_ZULIP_SERVICES_URL"] = "https://push.zulipchat.com"
        env["SETTING_ZULIP_SERVICE_PUSH_NOTIFICATIONS"] = "True"
    return env


# --------------------------------------------------------------------------- render cmd


def write_tree(r: Rendered, out: Path) -> None:
    (out / "servers").mkdir(parents=True, exist_ok=True)
    (out / "platform.json").write_text(dump_json(r.platform))
    (out / "index.json").write_text(dump_json(r.index))
    for name, spec in r.servers.items():
        (out / "servers" / f"{name}.json").write_text(dump_json(spec))


def tree_files(root: Path) -> dict[str, str]:
    if not root.is_dir():
        return {}
    return {str(p.relative_to(root)): p.read_text() for p in sorted(root.rglob("*")) if p.is_file()}


def cmd_render(args: argparse.Namespace) -> int:
    dept_dir = Path(args.dept_dir).resolve()
    cfg = load_config(dept_dir)
    rendered = render_config(cfg, dept_dir)
    for w in rendered.warnings:
        print(f"WARNING: {w}", file=sys.stderr)
    target = dept_dir / GENERATED
    if args.check:
        with tempfile.TemporaryDirectory() as tmp:
            write_tree(rendered, Path(tmp))
            want, have = tree_files(Path(tmp)), tree_files(target)
        if want == have:
            print(f"OK: {target} is up to date ({len(want)} files)")
            return 0
        for rel in sorted(set(want) | set(have)):
            if want.get(rel) != have.get(rel):
                diff = difflib.unified_diff(
                    (have.get(rel) or "").splitlines(True), (want.get(rel) or "").splitlines(True),
                    f"generated/{rel} (committed)", f"generated/{rel} (rendered)",
                )
                sys.stderr.writelines(diff)
        print(f"STALE: {target} does not match chat.yml; run tools/render.py render {args.dept_dir}", file=sys.stderr)
        return 1
    if target.exists():
        shutil.rmtree(target)
    write_tree(rendered, target)
    print(f"Rendered {len(rendered.servers)} server(s) into {target}")
    return 0


# --------------------------------------------------------------------------- resolve cmd


def app_fqdn(spec: dict[str, Any], default_domain: str) -> str:
    return f"{spec['app_name']}.{default_domain}"


def reachable_url(spec: dict[str, Any], realm_slug: str, default_domain: str) -> str | None:
    """Where a realm answers right now, or None if it is not reachable before DNS."""
    realm = next((r for r in spec["realms"] if r["slug"] == realm_slug and r["active"]), None)
    if realm is None:
        return None
    if spec["dns"] == "live":
        return f"https://{realm['live_host']}/"
    if realm["preview"]:
        return f"https://{app_fqdn(spec, default_domain)}/"
    return None


def redirects_conf(spec: dict[str, Any], peers: dict[str, dict[str, Any]], default_domain: str) -> tuple[str, list[str]]:
    lines = [f"# {HEADER_NOTE}", "# chat.<dept>/<slug> -> the group's own Zulip host (Zulip cannot live under a path)."]
    skipped = []
    for r in spec["redirects"]:
        target = peers.get(r["server"])
        url = reachable_url(target, r["realm"], default_domain) if target else None
        if url is None:
            skipped.append(r["slug"])
            continue
        lines.append(f"location ~ ^/{re.escape(r['slug'])}/?$ {{ return 302 {url}; }}")
    return "\n".join(lines) + "\n", skipped


def resolve_settings(spec, peers, default_domain, oidc_client_id, acs_mail_from=None) -> tuple[dict[str, str], list[str]]:
    fqdn = app_fqdn(spec, default_domain)
    live = spec["dns"] == "live"
    conf, skipped = redirects_conf(spec, peers, default_domain)
    # host=theme for each themed host: its live name, and the pre-DNS name for the realm
    # that answers there before DNS.
    theme_pairs = []
    for t in spec.get("themes", []):
        theme_pairs.append(f"{t['host']}={t['theme']}")
        if t["preview"]:
            theme_pairs.append(f"{fqdn}={t['theme']}")
    values = {
        "themes": " ".join(dict.fromkeys(theme_pairs)),
        "acs_mail_from": acs_mail_from or "",
        "external_host": spec["external_host_live"] if live else fqdn,
        "oidc_client_id": oidc_client_id,
        "redirects_b64": base64.b64encode(conf.encode()).decode(),
    }
    if spec["kind"] == "shared":
        hosts = {r["slug"]: r["live_host"] for r in spec["realms"] if r["active"]}
        if not live:
            hosts[spec["preview_realm"]] = fqdn
        values["realm_hosts"] = pylit(hosts)
        # Pending: the OIDC callback is served on the preview host itself. Live: one
        # callback host (auth.<external_host>) for every realm, so adding a realm needs
        # no Entra change.
        values["social_auth_subdomain"] = SOCIAL_AUTH_SUBDOMAIN if live else ""
    out = {}
    for key, val in spec["settings"].items():
        def sub(m: re.Match) -> str:
            k = m.group(1)
            if k not in values:
                raise ConfigError(f"{spec['name']}: no value for placeholder {{{{{k}}}}}")
            return values[k]
        rendered = re.sub(r"\{\{([a-z0-9_]+)\}\}", sub, val)
        check_setting(spec["name"], key, rendered)
        if "{{" in rendered:
            raise ConfigError(f"{spec['name']}: unresolved placeholder left in {key}: {rendered}")
        if rendered == "":
            continue  # docker-zulip skips empty SETTING_ values; don't send them
        out[key] = rendered
    return out, skipped


# docker-zulip's entrypoint (setConfigurationValue) writes SETTING_* into settings.py.
# It strips ALL whitespace from `echo -e "$value"` and, if that is shaped like [..], (..)
# or {..}, pastes the raw value in as Python code. Only these are meant to be literals
# (render builds them with pylit()).
PYTHON_LITERAL_SETTINGS = frozenset({"SETTING_SOCIAL_AUTH_OIDC_ENABLED_IDPS", "SETTING_REALM_HOSTS"})


def check_setting(server: str, key: str, value: str) -> None:
    if re.search(r"[\x00-\x1f\x7f]", value):
        raise ConfigError(f"{server}: {key} contains a control character")
    if not key.startswith("SETTING_"):
        return
    # `echo -e` turns \x28 into "(", \c truncates, ...: no escapes at all.
    if "\\" in value:
        raise ConfigError(f"{server}: {key} contains a backslash, which docker-zulip's echo -e would interpret: {value!r}")
    if key in PYTHON_LITERAL_SETTINGS:
        return
    stripped = re.sub(r"\s", "", value)
    # Stricter than docker-zulip (which also needs the matching closer at the end):
    # nothing that is not meant to be a literal may even start like one.
    if stripped[:1] in ("(", "[", "{"):
        raise ConfigError(f"{server}: {key} would be read as Python code: {value!r}")


def cmd_resolve(args: argparse.Namespace) -> int:
    spec_path = Path(args.server)
    spec = json.loads(spec_path.read_text())
    plat = json.loads((spec_path.parent.parent / "platform.json").read_text())
    peers = {p.stem: json.loads(p.read_text()) for p in spec_path.parent.glob("*.json")}
    client_id = args.oidc_client_id or spec["entra"]["client_id"]
    if not client_id:
        raise ConfigError(f"{spec['name']}: no Entra client id (pin entra.client_id or pass --oidc-client-id)")
    if not re.fullmatch(r"[0-9a-fA-F-]{36}", client_id):
        raise ConfigError(f"{spec['name']}: '{client_id}' is not an Entra client id")
    registry = args.registry
    if not re.fullmatch(r"[a-z0-9]{5,50}\.azurecr\.io", registry or ""):
        raise ConfigError(f"--registry must be the department's <name>.azurecr.io login server, not {registry!r}")
    # Only images built into (or imported to) the department's own registry, by digest.
    if not re.fullmatch(rf"{re.escape(registry)}/chat@sha256:[0-9a-f]{{64}}", args.image or "") and not args.allow_unpinned_image:
        raise ConfigError(f"--image must be {registry}/chat@sha256:<digest> (build-image.zsh); pass --allow-unpinned-image for local tests")
    # Pulled by digest alone (<repo>@sha256:...): build-image.zsh imported exactly that
    # digest under <repo>:<tag>, and a digest reference needs no tag.
    sidecars = {}
    for k, v in json.loads((TEMPLATE_ROOT / "image" / "sidecars.json").read_text()).items():
        if k.startswith("_"):
            continue
        m = re.fullmatch(r"(?:docker\.io/)?([a-z0-9][a-z0-9._/-]*):[A-Za-z0-9._-]+@(sha256:[0-9a-f]{64})", v)
        if not m:
            raise ConfigError(f"image/sidecars.json: {k} = {v!r} is not <repo>:<tag>@sha256:<digest>")
        sidecars[k] = f"{registry}/{m.group(1)}@{m.group(2)}"
    if "{{acs_mail_from}}" in json.dumps(spec["settings"]) and not args.acs_mail_from:
        raise ConfigError(f"{spec['name']}: ACS Azure-managed domain: pass --acs-mail-from DoNotReply@<domain>")
    if args.acs_mail_from and not re.fullmatch(r"[A-Za-z0-9._%+-]+@[A-Za-z0-9-]+(\.[A-Za-z0-9-]+)+", args.acs_mail_from):
        raise ConfigError(f"--acs-mail-from {args.acs_mail_from!r} is not an address")
    settings, skipped = resolve_settings(spec, peers, args.default_domain, client_id, args.acs_mail_from)
    for slug in skipped:
        print(f"WARNING: redirect /{slug} omitted: its target is not reachable until DNS is live", file=sys.stderr)
    custom_domains = json.loads(args.custom_domains) if args.custom_domains else []
    ip_rules = json.loads(args.ip_rules) if args.ip_rules else []
    if spec["ip_gate"] and not ip_rules:
        raise ConfigError(f"{spec['name']}: ip_gate is on but no IP rules were supplied; refusing to deploy it open")
    if not spec["ip_gate"] and ip_rules:
        raise ConfigError(f"{spec['name']}: ip_gate is off but IP rules were supplied")
    params = {
        "location": plat["region"],
        "environmentName": plat["names"]["environment"],
        "appIdentityName": spec["identities"]["app"]["name"],
        "dbIdentityName": spec["identities"]["db"]["name"],
        # The -hc job's own identity (it reads only the ping key); empty without healthchecks.
        "hcIdentityName": spec["identities"].get("hc", {}).get("name", ""),
        "keyVaultName": plat["names"]["key_vault"],
        "storageAccountName": plat["names"]["storage"],
        "postgresHost": plat["postgres"]["host"],
        "postgresAdminUser": plat["postgres"]["admin_user"],
        "acaSubnet": plat["network"]["aca_subnet"],
        "tenantId": plat["tenant_id"],
        "serverName": spec["name"],
        "appName": spec["app_name"],
        "mgmtJobName": spec["jobs"]["mgmt"],
        "dbinitJobName": spec["jobs"]["dbinit"],
        "hcJobName": spec["jobs"]["hc"],
        "healthchecksEnabled": plat["healthchecks"]["enabled"],
        "healthchecksPingBase": plat["healthchecks"]["ping_base"],
        "healthchecksSlug": spec["healthchecks"]["health"],
        "healthchecksCron": f"*/{plat['healthchecks']['health_interval_minutes']} * * * *"
                            if plat["healthchecks"]["health_interval_minutes"] < 60 else "0 * * * *",
        "databaseName": spec["database"]["name"],
        "shareName": spec["share"],
        "envStorageName": spec["env_storage"],
        "dataQuotaGiB": spec["data_quota_gib"],
        # Sidecars take 0.25 vCPU / 0.5 GiB each; Zulip gets the rest.
        "zulipCpu": f"{spec['cpu'] - 0.75:g}",
        "zulipMemory": f"{spec['cpu'] * 2 - 1.5:g}Gi",
        "image": args.image,
        "registryServer": registry,
        "sidecarImages": sidecars,
        "zulipEnv": [{"name": k, "value": v} for k, v in sorted(settings.items())],
        "keyVaultSecretNames": spec["key_vault_secrets"],
        "customDomains": custom_domains,
        "ipSecurityRestrictions": ip_rules,
        "easyAuth": spec["easy_auth"],
        "easyAuthExcludedPaths": spec["easy_auth_excluded_paths"],
        "oidcClientId": client_id,
        "deployApp": args.deploy_app,
    }
    print(dump_json({
        "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentParameters.json#",
        "contentVersion": "1.0.0.0",
        "parameters": {k: {"value": v} for k, v in params.items()},
    }), end="")
    return 0


def cmd_urls(args: argparse.Namespace) -> int:
    dept_dir = Path(args.dept_dir).resolve()
    servers_dir = dept_dir / GENERATED / "servers"
    specs = {p.stem: json.loads(p.read_text()) for p in sorted(servers_dir.glob("*.json"))}
    if not specs:
        raise ConfigError(f"{servers_dir}: nothing rendered")
    rows = []
    for name, spec in specs.items():
        for r in spec["realms"]:
            url = reachable_url(spec, r["slug"], args.default_domain)
            rows.append({
                "server": name, "realm": r["slug"] or "(root)", "dns": spec["dns"],
                "now": url or "not reachable until DNS is live",
                "live": f"https://{r['live_host']}/",
            })
    if args.json:
        print(dump_json(rows), end="")
    else:
        for row in rows:
            print(f"{row['server']:<12} {row['realm']:<20} {row['dns']:<8} now: {row['now']}  live: {row['live']}")
    return 0


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)
    r = sub.add_parser("render")
    r.add_argument("dept_dir")
    r.add_argument("--check", action="store_true")
    r.set_defaults(func=cmd_render)
    s = sub.add_parser("resolve")
    s.add_argument("--server", required=True, help="generated/servers/<name>.json")
    s.add_argument("--default-domain", required=True, help="Container Apps environment default domain")
    s.add_argument("--image", required=True, help="<registry>/chat@sha256:... from build-image.zsh")
    s.add_argument("--registry", required=True, help="the department ACR login server, <name>.azurecr.io")
    s.add_argument("--allow-unpinned-image", action="store_true")
    s.add_argument("--oidc-client-id")
    s.add_argument("--custom-domains", help="JSON array of live customDomains to preserve")
    s.add_argument("--ip-rules", help="JSON array of ipSecurityRestrictions")
    s.add_argument("--deploy-app", type=lambda v: v.lower() == "true", default=True)
    s.add_argument("--acs-mail-from", help="DoNotReply@<Azure-managed domain> (email.acs.domain: azure-managed)")
    s.set_defaults(func=cmd_resolve)
    u = sub.add_parser("urls")
    u.add_argument("dept_dir")
    u.add_argument("--default-domain", required=True)
    u.add_argument("--json", action="store_true")
    u.set_defaults(func=cmd_urls)
    args = ap.parse_args(argv)
    try:
        return args.func(args)
    except ConfigError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    sys.exit(main())
